### PR TITLE
Use cw-ownable in the proxy

### PR DESCRIPTION
**Pull request by adairrr**
This change updates the `proxy` to use `cw-ownable`. Since the proxy is first owned by the `account-factory` and then transferred to the `manager`, a new `ExecuteMsg::AcceptProxyOwnership` was added to the `manager`. 

The ownership transfer is initiated by the `account-factory` and a new submessage was added to the Account-creation process to first transfer the ownership to the manager and then accept it through this new entry-point.

The logic for accepting the ownership does the following:
1) Check that the caller is the `account-factory`
2) Check the account id of the proxy and the manager to ensure they match
3) Accept the ownership as the manager

### CODE REVIEW

**Comment by adairrr** [comment]
Task linked: [CU-34aj8eb Change Admin update function to use Secure Admin](https://app.clickup.com/t/34aj8eb)

**Comment by CyberHoward** [comment]
hmmm does this even make sense for us to do in the proxy contract? I'm not a fan.

**Comment by adairrr** [comment]
> Secure admin is effective in preventing human error on admin changes but I doubt its value in this contract.

Good point. Do we need to make sure that the user doesn't call `ExecOnModule(proxy, SetAdmin)?`

**Comment by CyberHoward** [comment]
> > Secure admin is effective in preventing human error on admin changes but I doubt its value in this contract.
> 
> Good point. Do we need to make sure that the user doesn't call `ExecOnModule(proxy, SetAdmin)?`

I think it's ok that they can if the want to. Maybe someone will have a use-case for it.

**Comment by adairrr** [comment]
If it's transferred to a smart-contract, it would be difficult to `AcceptOwnership`.

**Pull request closed without merging**
