### PR TITLE
 Use cw-ownable in the ANS Host

### PR DESCRIPTION
**Pull request by adairrr**
This change first adds two macros to our `abstract-sdk` for `cw-ownable`: one for executing the ownership update and the other for querying the ownership. This *execute* macro is, however, specific to our repositories as it takes in the specific AbstractResponse so perhaps it should be moved elsewhere?

This is so that we refrain from duplicating the code everywhere in the codebase.

It also highlights use of the macros by updating the ANS host to use `cw-ownable` in lieu of just plain `Admin` objects.

### CODE REVIEW

**Comment by adairrr** [comment]
Should we block the `renouncing` of ownership which is (by-default) possible with cw-ownable?

**Comment by CyberHoward** [comment]
I think it's arguable if we really need a macro for these functions but it probably does make sense. For smart-contracts in general we want to keep it as interpretable as possible because we want other developers to be able to verify our contracts. If we use macro's everywhere that complicates the process of figuring out what's going on in the contract. Just something to keep in mind.

**Comment by CyberHoward** [comment]
> Should we block the `renouncing` of ownership which is (by-default) possible with cw-ownable?

Nah, I thing this is good.

**Review by CyberHoward — APPROVED** [review]

**Comment by adairrr** [comment]
> I think it's arguable if we really need a macro for these functions but it probably does make sense. For smart-contracts in general we want to keep it as interpretable as possible because we want other developers to be able to verify our contracts. If we use macro's everywhere that complicates the process of figuring out what's going on in the contract. Just something to keep in mind.

Yeah absolutely. Just plopped it into a macro cause we'll be using it in at least 8 contracts and way easier to change one thing than 8. Especially if we were to block certain actions.

**Comment by adairrr** [comment]
Actions are failing weirdly. 

https://github.com/Abstract-OS/contracts/actions/runs/4600086624/jobs/8126264122?pr=281

```
Failed to resolve action download info. Error: Circuit Breaker "HttpClientThrottler-GitHubVssHttpClientRequester-launch-receiver.githubapp.com" short-circuited. In the last 10000 milliseconds, there were: 0 failure, 0 timeout, 65 short circuited, 0 concurrency rejected, and 0 limit rejected. Last exception: Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException Internal Server Error

```

**Pull request merged**
