### PR TITLE
Rename OS to Account

### PR DESCRIPTION
**Pull request by adairrr**
## :loudspeaker: Type of change

:white_small_square: Bugfix
:white_small_square: New feature
:white_small_square: Enhancement
:white_small_square: Refactoring
:white_small_square: Maintenance

## :scroll: Description and Motivation

This change removes the "os" from Abstract. It also renames "Core" to "AccountBase" as a major change. 

abstract-os package -> abstract-interface
abstract_sdk.os -> abstract_sdk.interfaces (maybe should be interface)?

- OS to AbstractOS and OsFactory to AccountFactory
- Os factory to account factory
- Abstract OS to Abstract
- AbstractOsError to AbstractError
- Os Id to account id
- OsCore to AccountBase
- extern os to interfaces
- os vars to account
- OS to Account
- os to account
- abstract-os to abstract-interface
- Remove remaining references to OS

## :pencil: Checklist

:white_small_square: Reviewed submitted code
:white_small_square: Added tests to verify changes
:white_small_square: Updated docs
:white_small_square: Verified on testnet

### CODE REVIEW

**Comment by CyberHoward** [comment]
Awesomee, can you check out the failing tests?

**Comment by CyberHoward** [comment]
`iabstract`? hmmm don't really like that one...

**Comment by adairrr** [comment]
> `iabstract`? hmmm don't really like that one...

Do you prefer abstract-interface?

**Comment by adairrr** [comment]
> Awesomee, can you check out the failing tests?

Ah, was the doctest.

**Comment by CyberHoward** [comment]
> > `iabstract`? hmmm don't really like that one...
> 
> Do you prefer abstract-interface?

abstract-core? Because it also includes the objects and contract states

**Comment by adairrr** [comment]
Conflicts do be annoying. Had to do a full merge.

**Review by CyberHoward — APPROVED** [review]
Lgtm

**Pull request merged**
